Testing: Husky Setup
IAmRiteshKoushik/ace-ops pull request #12
Opened 2024-10-09 09:20 UTC by IAmRiteshKoushik

> This PR is still WIP.

This PR introduces the following:
1. `.husky/` for pre-commit hooks (needed to maintain single lock file)
2. Prettier and ESLint for consistent linting and formatting across the project. (var names, case-ing, code quality checks etc)
3. Issue Template in `.github/` 
4. PR Template in `.github/`

Review and merge @Ashrockzzz2003

2024-10-09 09:21 UTC, IAmRiteshKoushik commented
@Ashrockzzz2003 Would it be a good idea to introduce CI to check the build before merging the PRs ?

2024-10-09 12:12 UTC, Ashrockzzz2003 commented
> @Ashrockzzz2003 Would it be a good idea to introduce CI to check the build before merging the PRs ?

Yep 
It's better to have to ensure lesser trouble in deployment.

2024-10-09 12:18 UTC, Ashrockzzz2003 requested changes

2024-10-09 12:18 UTC, Ashrockzzz2003 commented on .github/ISSUE_TEMPLATE/bug.md
Add about linking correct labels to the issue and rules for who to assign to.

2024-10-09 12:18 UTC, Ashrockzzz2003 commented on .github/ISSUE_TEMPLATE/chore.md
Include about listing tasks and subtasks with this format 

```md
- [ ] task
```

2024-10-09 12:18 UTC, Ashrockzzz2003 commented on .github/ISSUE_TEMPLATE/feature.md
Probably mention about adding the tasks it would involve too if possible.

2024-10-09 12:18 UTC, Ashrockzzz2003 commented on .github/PULL_REQUEST_TEMPLATE.md
How about a TL;DR for every PR on top for quick identification.

2024-10-11 13:32 UTC, IAmRiteshKoushik commented on .github/PULL_REQUEST_TEMPLATE.md
A simple description should suffice. The project is not expecting a huge inflow of contributors. This template is added only to make things easier for @Nandgopal-R @adarsshkg-codebank and the upcoming maintainers of this project. Simple description should suffice.

2024-10-11 13:33 UTC, IAmRiteshKoushik commented on .github/ISSUE_TEMPLATE/feature.md
Nice one. Have added this in the latest commit.

2024-10-11 13:34 UTC, IAmRiteshKoushik commented on .github/ISSUE_TEMPLATE/chore.md
This change is added in the latest commit where a person creating an issue gets the option to add subtasks which might associated so that the contributors and maintainers get better clarity on the things to address.

2024-10-11 13:35 UTC, IAmRiteshKoushik commented on .github/ISSUE_TEMPLATE/bug.md
Label linking will always remain fairly subjective. Again, not expecting huge inflow of contributors. Will throw in a tip or two.

2024-10-11 13:36 UTC, IAmRiteshKoushik commented
> > @Ashrockzzz2003 Would it be a good idea to introduce CI to check the build before merging the PRs ?
> 
> Yep It's better to have to ensure lesser trouble in deployment.

Can you open a PR and help out with this. Have already added the `workflows` directory

2024-10-20 18:29 UTC, Nandgopal-R approved these changes

2024-10-20 19:59 UTC, Nandgopal-R approved these changes

2024-10-20 20:53 UTC, merged